### ISSUE TITLE
Tracking issue for dependency work

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/analyzer-lsp#152]
- [x] https://github.com/konveyor/analyzer-lsp/issues/151
- [x] https://github.com/konveyor/analyzer-lsp/issues/140
- [x] https://github.com/konveyor/analyzer-lsp/issues/135
- [x] https://github.com/konveyor/analyzer-lsp/issues/102
- [x] https://github.com/konveyor/analyzer-lsp/issues/83
