### ISSUE TITLE
API Review Tracking Issue

### ISSUE THREAD

**Issue by shawn-hurley** [konveyor/analyzer-lsp#165]
## HubAPI
- [x] Remove all occurrences of RulesetTechnology
- [x] Remove labels from Ruleset
- [x] #171

## Violations
- [x] Remove AnalysisID & Tags
- [x] #170
- [x] #169

### Incidents
- [ ] Pull up `lineNumber` from `Extras` to `Incident`

### Rule
- [x] Add basic validation for RuleIDs (newlines/colon)
- [x] Add description field to Rules
- [x] For row display, UI to use the first line from description --> @pranavgaikwad I think we should make an issue somewhere else for this.
- [x] Links should not be treated as metadata, move it to actions
- [x] Links to be added to violation only when message is set

## Provider Settings
- [ ] #174
- [x] Change providerSpecificConfig to map[string]interface{} type
- [x] Change Java bundles to a list of strings

## Provider Interface
- [x] Remove HasCapability() function, handle it via outside helper function
- [x] Make use of the returned integer by Init() in the Evaluate() call
- [x] Pull Dependencies() functions out of embedded struct
- [x] Rename DepLinkedList() function to something better like a DepGraph() :wink:

## Dependencies
- [x] Rename SHA to ResolvedIdentifier :wink-again:
- [x] Add a new Extras field to store more info about a dependency
